### PR TITLE
Fix: make aicore-notification-perf build and measure again

### LINKED ISSUE #2333: [Bug] aicore-notification-perf does not build or run on CANN 9.0.0 (six defects; fixes exist in aicore-fin-ordering)
### Platform

a2a3 (Ascend 910B/C hardware)

### Runtime Variant

All / Unknown

### Description

`tools/cann-examples/aicore-notification-perf` does not build or run on CANN
9.0.0. Five separate things stop it, each of which costs a debugging round-trip
to rediscover; a sixth means its COND subtest reports "no valid samples" rather
than the effect it is measuring.

I hit all six while extending the tool into
`tools/cann-examples/aicore-fin-ordering` (#2317), where each is already fixed —
so this issue is a backport, and the fixes can be lifted from that directory.

**1. `kernel_operator.h` not found.** The CMake include list is
`${ASCEND_HOME_PATH}/include{,/external,/c_api,/c_api/internal}`, but on CANN
9.x the AscendC headers live under the arch subtree:
`${ASCEND_HOME_PATH}/aarch64-linux/tikcpp/tikcfw{,/impl,/interface}`.

**2. `cannot find -lascend_hal`.** `libascend_hal.so` ships with the driver,
which is a *sibling* of the toolkit rather than a subdirectory of it, and is not
under `lib64` — `/usr/local/Ascend/driver/lib64/driver`.

**3. `rtRegisterAllKernel` rejects the producer with `107000`.** The tool
registers the raw `ccec -c` object. A linked device ELF is required:
`ld.lld -m aicorelinux -Ttext=0 -static -n`, the same link line
`src/a2a3/platform/onboard/aicore/CMakeLists.txt` uses.

**4. Still `107000` after linking.** `rtRegisterAllKernel` enumerates kernels by
the mix-kernel symbol pair `<name>_0_mix_aic` / `<name>_0_mix_aiv`, and the ELF
must carry **both** halves — so the source compiles twice (cube + vec) and both
objects link into one image. The tool's entry is plainly named
`notif_perf_producer`, so neither symbol exists. Mirrors the `KERNEL_ENTRY`
macro in `src/a2a3/platform/onboard/aicore/kernel.cpp`.

**5. `duplicate symbol: g_tilingKey` once both halves compile.** AscendC's
`kernel_operator.h` defines non-weak globals, so it can only be included in one
half. The runtime's own AICore sources avoid that header entirely for the same
reason.

**6. The COND subtest silently reports "no valid samples".** Two causes, in
order:

- `block_dim=1` does not pin the producer to AIC[0], but the consumer polls the
  COND register for a hardcoded `target_core_idx`. The producer must report its
  own core, the way `aicore_execute` reports `physical_core_id`. **And that id
  must be masked with `0x0FFF`** before indexing the AIC_CTRL window, as
  `get_physical_core_id()` does — the raw `get_coreid()` (observed `0x8010`)
  addresses outside the window and *faults the AICPU op*, surfacing as
  `507018 / aicpu exception`.
- Even with the right core, `SampleCondE2E` discards any sample whose
  `t_obs <= tw` (`consumer.cpp`), and `tw` is read from GM right after
  observing COND. When that read is stale the sample is dropped instead of
  recorded, so the subtest reports zero samples rather than surfacing the
  ordering effect. That effect is real and now measured — see #2233 and the
  matrix in `aicore-fin-ordering`.

### Steps to Reproduce

```bash
export ASCEND_HOME_PATH=/usr/local/Ascend/ascend-toolkit/latest
cd tools/cann-examples/aicore-notification-perf/device-aicore
cmake -B build -S . -DCCE_AICORE_ARCH=dav-c220-cube && cmake --build build
```

Fails at (1). Fixing each in turn walks through (2)–(6).

### Expected Behavior

The tool builds and reports latency for both notification paths, as its README
describes.

### Actual Behavior

Does not compile; after (1)–(2) does not register; after (3)–(5) runs but the
COND path reports `COND no valid samples`.

### Git Commit ID

b8e9dfe98

### CANN Version

9.0.0

### Driver Version

26.0.rc1 (`ascendhal_version=7.35.23`)

### Host Platform

Linux (aarch64)

### Additional Context

Nothing in CI builds this tool. `_ut-npu-a5.yml` / `_ut-npu-a2a3.yml` build
`tools/cann-examples/`'s `query`, `aicpu-device-query` and
`aicpu-kernel-launch` by name, and `aicore-notification-perf` is not among them
— which is how it rotted unnoticed. Adding it to that list would keep it honest,
and is arguably the more valuable half of the fix.

### PR DESCRIPTION
**Pull request by ChaoWao**
## Summary

Fixes #2333. The tool did not compile on CANN 9.0.0, and once the build was
repaired its COND subtest reported `no valid samples` instead of a latency.
Nothing in CI built it, which is how it rotted unnoticed.

### Build

| defect | fix |
| --- | --- |
| `kernel_operator.h` not found | **the header is not needed at all** — dropped from this tool *and* from `aicore-fin-ordering` |
| `cannot find -lascend_hal` | ships with the driver, a *sibling* of the toolkit, not under its `lib64` |
| `rtRegisterAllKernel` → `107000` | it takes a linked device ELF, not a raw `ccec -c` object |
| still `107000` | the ELF must carry **both** halves of the `_0_mix_aic` / `_0_mix_aiv` pair, so the source compiles twice and `ld.lld` links the pair |
| `duplicate symbol: g_tilingKey` | dissolved by the first row — the header that defined it is gone |

On the first defect: the issue proposes pointing the include path at
`aarch64-linux/tikcpp/tikcfw`, and I did that first. **It worked locally and
still failed on the CI runner**, whose toolkit puts `tikcpp` elsewhere — the
`ut-a2a3` / `ut-a5` red on the first push of this PR. Neither producer references
a single `AscendC::` name; `dcci`, `dsb`, `set_cond`, `get_coreid` and
`get_sys_cnt` are `-x cce` builtins, and the runtime's own AICore sources include
no AscendC header either. Removing the include fixes the missing header at its
source instead of tracking one release's layout, dissolves the duplicate
`g_tilingKey`, and drops **205 of the compile's 206 warnings** — all of which
came from that header.

### Measurement

- **`block_dim=1` does not pin the producer to AIC[0], and the core is not stable
  between runs** — two runs of the same binaries reported `0x8015 → 21` and
  `0x8 → 8`. The consumer polled a hardcoded index, so it watched a register that
  never changed and timed out. The producer now reports its own core; the consumer
  masks with `0x0FFF` before indexing the AIC_CTRL window, as the runtime does.
  An unmasked id addresses outside the window and faults the AICPU op.
- **The report is published after `go=1`, not at kernel entry.** The consumer
  clears `core_id_valid` during setup and the producer reports once, so an
  entry-time report was erased and never repeated. Not in the issue — I
  introduced it, hit it, and it is why the first hardware run still failed.
- **The consumer invalidates the line each poll**, because it wrote
  `core_id_valid = 0` itself — its own copy is valid, and an AICore write to that
  line does not reach a plain re-read. The wait is bounded **in time, not in
  iterations**: each poll carries a full `dc civac; dsb sy; isb`, and my first
  attempt at a 20M-iteration bound overshot the op-execute timeout, killed
  `aicpu-sd`, and hung the run for the full 900 s lock.
- **The producer's COND path pairs its `dcci` with a `dsb` before `set_cond`** —
  same requirement as the runtime's FIN path (#2233 / #2324). `dcci` issues the
  write-back without waiting and the SPR write does not travel with it, so the
  consumer could observe the notification and still read the previous timestamp.
- **Samples are counted, not dropped.** `t_obs <= tw` used to be discarded
  silently, turning a publication-ordering fault into "no valid samples" — which
  reads as a broken harness. The launcher now prints that count, the core id, and
  whether the producer or the fallback supplied it (a reported id of `0` could not
  be told from a fallback default of `0`).

### The hang CI found, and no local sweep did

After the above, the a2a3 job hung for the full harness bound and reported an
**empty** output tail. Root cause is in the handshake layout: `go` and `mode` —
the AICPU's control words — shared a 64 B cache line with `p_seq` and `p_tw`,
which the producer writes. The producer publishes with
`dcci(..., CACHELINE_OUT)`, which writes back the *whole line* from a cache the
AICore's GM reads do not keep coherent, so every publish also restored the
producer's stale copy of the control words. A `go = 0` landing between the
producer's invalidate and its write-back was undone, its `while (go != 0)` loop
never exited, and the host blocked in `aclrtSynchronizeStream` — which takes no
timeout. The header had recorded the overlap as a "pre-existing hazard" without
connecting it to a failure.

The window's width **is** the producer's throttle, so the mechanism is measurable
rather than argued — at `throttle_iter = 0` the window is nearly the whole
iteration, at 5000 a small fraction of it:

| `throttle_iter` | before | after |
| --- | --- | --- |
| 0 | 0/6 pass (2 hang, 4 fail) | **6/6 pass** |
| 50 (as shipped) | 3/6 pass (3 hang) | **6/6 pass** |
| 5000 | 6/6 pass | 6/6 pass |

- **One writer per cache line** — consumer control on line 0, producer samples on
  line 1, producer report on line 2, with `static_assert`s on all three offsets so
  a future field cannot quietly re-share a line.
- **The consumer cleans line 0 after each control write**, since the producer reads
  those words after invalidating its own copy of the line.
- **Both producer waits are bounded** (~5 s for the release, ~10 s for the run) and
  it records how it left in `producer_rc`, which the launcher prints and the pass
  condition includes. A missed handshake now ends the kernel and names itself
  instead of holding a stream open for the harness to kill.
- **The harness says why its tail is empty** — a SIGTERM'd tool never flushes its
  stdio buffer — and its bound drops 600 s → 120 s. Every tool here finishes in
  seconds, so all the old bound bought was ten minutes of a locked NPU per hang.

### CI

CI stops naming tools and starts discovering them. Both workflows call
`tools/build_cann_examples.sh`, which walks `tools/cann-examples/*/` and builds
each tool by recognising its layout (bare `CMakeLists.txt`; `device/` + `host/`;
`device-aicore/` + `device-aicpu/` + `host/`). A tool matching none of them is
**reported**, not skipped, so a new shape is a visible failure rather than silent
non-coverage — and adding a tool needs no workflow edit.

The by-name list was the actual defect: it grew one entry per rot incident, so a
tool nobody listed was a tool nobody compiled. Proving it, `aicpu-mmio-probes` was
failing to link at the same time, with the same missing driver path, and nothing
was watching it.

**And the gate runs them, not just builds them.** Each tool carries its own
`smoke.sh` taking a device id, because the env var names it reads, the directory it
runs from and the argv that makes a short run all differ per tool — a shared runner
cannot know them, and a by-name list in CI would have to. A tool with no
`smoke.sh` is reported as build-only, so a gap in *run* coverage is a number in the
summary instead of a silence. A smoke may decline an arch by exiting 77 with a
reason, counted separately from passes and failures; three do, all because their
runtime constants are a2a3's while their code compiles for either arch:

| Tool | Why it skips on a5 |
| ---- | ------------------ |
| `aicore-notification-perf` | hardcodes a2a3's `REG_SPR_COND_OFFSET` `0x4C8`; a5 is `0x5108` |
| `aicore-fin-ordering` | same |
| `aicpu-mmio-probes` | `halMemCtl` exists only under `src/a2a3/`; a5 returns rc=65534 with a null AIC_CTRL base |

So a sweep is **7 built + 7 run** on a2a3, and **7 built + 4 run + 3 skipped** on
a5. Making those three per-arch would remove the skips and is not attempted here —
this box has no a5 silicon to verify it on.

Running them is what found the last defects. `aicore-fin-ordering`'s bisect stages
1–3 stop early and exit non-zero with an empty table, so a smoke pointed at one
looks like a failure; its `smoke.sh` uses stage 0. Each of the three arch skips
above was found by the a5 arm failing, one per push — all three *compile* on a5, so
no amount of build coverage would have said anything about them. Then the cache-line
hang came from the a2a3 arm.

The driver-package lookup that broke two tools is now one shared module,
`cann-examples/cmake/ascend_driver_path.cmake`. Three spellings had accumulated
across the five tools that link `libascend_hal.so` — a resolution with a
configure-time check (`query`), a hardcoded `/usr/local/Ascend/driver`, and nothing
at all — and the one with nothing at all did not build. The shared copy keeps
`query`'s order (`-DASCEND_DRIVER_PATH`, then the sibling of `ASCEND_HOME_PATH`,
then the standard install) and its `FATAL_ERROR` naming the missing library, which
beats a bare `cannot find -lascend_hal`.

## Testing

a2a3, CANN 9.0.0, driver 26.0.rc1, one die locked via `task-submit`:

```text
=== notification-perf result ===
  consumer_rc        = 0
  magic              = 0xc0decafe  OK
  observed_p_seq     = 737 (must be > 0)
  producer_rc        = 0 (OK, stopped by the consumer)

  --- Phase 14: E2E AICore->AICPU latency ---
  GM   N=50  avg=21 ticks (~420 ns)  min=21 (~420 ns)  max=29 (~580 ns)
  COND N=50  avg=11 ticks (~220 ns)  min=4 (~80 ns)  max=37 (~740 ns)
  producer core_id   = 0x3 raw -> 3 used  [reported by producer]
```

- [x] **7 built + 7 run** through `build_cann_examples.sh --run` on a locked a2a3 die
- [x] **18 of 18** runs pass across the three `throttle_iter` arms above (the same
      arms were 9/18 before the layout fix, and 0/6 at `throttle_iter = 0`)
- [x] a5 arch (`dav-c310-cube`) builds all seven, including the new 192-byte
      layout's `static_assert`s — **not run**, this box's `onboard-arch-precheck`
      does not pass a5
- [x] The a5 arm's skip selection verified by simulation: both AICore tools report
      exit 77 with their reason under `SIMPLER_SMOKE_ARCH=a5`
- [x] `nm` confirms both `notif_perf_producer_0_mix_aic` and `_0_mix_aiv` in a
      statically-linked device ELF
- [x] `check_headers`, `check_english_only`, `check_retired_names`,
      `check_kernel_wire_isolation`, `clang-format` and `markdownlint-cli2` clean
      (`cpplint` is not installed on this box — left to the CI `pre-commit` job)

The README's expected-output block carries these measured numbers, and its protocol
diagram now matches the code: it had documented a `go`-bouncing handshake the
consumer abandoned, with the LDR sweeps mid-run instead of once at the end.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: tools/cann-examples/aicore-notification-perf/device-aicpu/consumer.cpp [hunk 1]
```diff
@@ -250,10 +275,55 @@ __attribute__((visibility("default"))) int simpler_aicpu_run(void *args) {
     hank->throttle_iter = 50;
     hank->p_seq = 0;
     hank->p_tw = 0;
+    hank->core_id_valid = 0;
```
[the remark this answers is not in the document]
Comment (ChaoWao) [reply tools/cann-examples/aicore-notification-perf/device-aicpu/consumer.cpp:298]: Fixed — and this is a real one I had half-solved. Thank you.

I moved the producer's *report* after `go == 1` to stop the consumer's reset from
erasing it, but left the reset itself unflushed, so the same race survives through
a different route: `dc civac` in the poll loop is clean-**and**-invalidate, so a
line the AICPU left dirty gets written back by the first poll — after the producer
has already published into it — restoring the stale `0`. The poll then falls back
to `target_core_idx` and can watch a register that never changes until timeout,
which is exactly the failure mode this PR exists to remove.

Now cleans the line after the reset and before `go = 1`, via a `CleanLine` helper
(`dc cvac; dsb sy`) next to the existing `InvalidateLine`. The comment on it says
why clean rather than clean-and-invalidate is the right instruction here, so the
next reader does not collapse the two.

Re-verified on a2a3 onboard hardware:

```text
consumer_rc        = 0
GM   N=100  avg=22 ticks (~440 ns)
COND N=100  avg=11 ticks (~220 ns)
producer core_id   = 0xa raw -> 10 used  [reported by producer]
```

Incidentally that run landed on core 10, where earlier runs landed on 21 and 8 —
three different cores across three runs of the same binaries, which is the
reason the producer has to report its own core at all.

File: tools/cann-examples/aicore-notification-perf/device-aicpu/consumer.cpp [hunk 2]
```diff
@@ -127,8 +145,11 @@ int SampleGmE2E(volatile NotifPerfHandshake *hank, uint32_t n_samples, NotifPerf
             if (d < min_v) min_v = d;
             if (d > max_v) max_v = d;
             taken++;
+        } else {
+            unordered++;
         }
     }
+    result->gm_unordered = unordered;
```
[the remark this answers is not in the document]
Comment (ChaoWao) [reply tools/cann-examples/aicore-notification-perf/device-aicpu/consumer.cpp:171]: Fixed. Both samplers now store the unordered count in their timeout branch as
well as on the normal path.

This one matters more than "Minor" suggests given what the PR is for: the count
exists precisely so a publication-ordering fault reports as a number instead of as
`no valid samples`. A timeout arriving after an unordered observation would have
reported `0` unordered — reintroducing the silent loss the count was added to
remove, in the one situation where the reader most needs it.

The comment at the GM site says that, so the coupling is visible to whoever edits
these branches next.

**Comment by ChaoWao** [comment]
@coderabbitai — answering the two surfaces that carry no resolve bit.

**Review summary (both inline findings):** fixed and the threads are resolved — the core-id line is cleaned after the `core_id_valid = 0` reset and before `go = 1`, and both sampling timeout branches now assign `gm_unordered` / `cond_unordered` before returning.

**Out-of-Scope Changes check** — superseded. That warning was against a revision where each workflow listed tools by name; the by-name list is gone. Both workflows now call `tools/build_cann_examples.sh`, which discovers every tool under `cann-examples/` by its layout. Naming fin-ordering was the thing being objected to, and no tool is named any more — which is also what caught `aicpu-mmio-probes` failing to link with nothing watching it.

**Merge-risk note** ("the COND measurement can poll the wrong core and time out") — that is the defect this PR fixes: the producer reports its own `get_coreid()`, the consumer masks it with `0x0FFF` and range-checks before indexing the AIC_CTRL window, and `core_id_from_producer` distinguishes a reported 0 from a fallback 0.

Since that review, CI found one more defect that no local sweep had: the tool hung for the full harness bound with an empty output tail. `go`/`mode` shared a 64 B cache line with the producer-written `p_seq`/`p_tw`, and the producer's `dcci(..., CACHELINE_OUT)` writes back the whole line — restoring its stale `go = 1` over the consumer's `go = 0`. The handshake is now one writer per cache line. The window's width is the producer's throttle, so the mechanism is measurable rather than argued:

| `throttle_iter` | before | after |
| --- | --- | --- |
| 0 | 0/6 pass | 6/6 pass |
| 50 (shipped) | 3/6 pass | 6/6 pass |
| 5000 | 6/6 pass | 6/6 pass |
